<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

// use PHPMailer\PHPMailer\PHPMailer;
// use PHPMailer\PHPMailer\Exception;


// Load Composer's autoloader
require 'vendor/autoload.php';

// require 'vendor/PHPMailer/src/Exception.php';
// require 'vendor/PHPMailer/src/PHPMailer.php';
// require 'vendor/PHPMailer/src/SMTP.php';

// Instantiation and passing `true` enables exceptions
$mail = new PHPMailer(true);

if (isset($_POST['submit'])) {
    $from = "noreply@atogeophysical.com";
    $to = "info@atogeophysical.com";
    $cc = $_POST['cc'];
    $bcc = $_POST['bcc'];
    $name = $_POST['name'];
    $email = $_POST['email'];
    $phone = $_POST['phone'];
    $subject = $_POST['subject'];
    $message = $_POST['message'];
    $msg = "<div>
    <h1>Subject ". $subject ."</h1>
    <br>
    <h3>Name ". $Name ." </h3>
    <br>
    <h3>Email ". $Email ." </h3>
    <br>
    <h3>Phone ". $phone ." </h3>
    <br>
    <h3>Message: ". $message ."</h3>
    <br></div>";

    try {
        //Server settings
        // $mail->SMTPDebug = SMTP::DEBUG_SERVER;

        // $mail->isSMTP(); 
        // $mail->Host       = 'smtp.mailtrap.io'; 
        // $mail->SMTPAuth   = true;
        // $mail->Username   = '192bf88d9c5bef';
        // $mail->Password   = 'a3636acac91698'; 
        // $mail->SMTPSecure = 'tls'; 
        // $mail->Port       = 2525;

        $mail->isSMTP();
        $mail->Host = 'atogeophysical.com';
        $mail->SMTPAuth = true;
        $mail->Username = 'noreply@atogeophysical.com'; //paste one generated by Mailtrap
        $mail->Password = 'DNl]NPrL?$9X';//paste one generated by Mailtrap
        $mail->SMTPSecure = 'tls';
        $mail->Port = 25;
    
        //Recipients
        $mail->setFrom($from);
        $mail->addAddress($to);
        $mail->addReplyTo($email);
        // if(!empty($cc)){
        //     $mail->addCC($cc);
        // }
        // if(!empty($bcc)){
        //     $mail->addBCC($bcc);
        // }
    
        // Attachments
        // $mail->addAttachment('/var/tmp/file.tar.gz');
        // $mail->addAttachment('/tmp/image.jpg', 'new.jpg');
    
        // Content
        $mail->isHTML(true);
        $mail->Subject = $subject;
        $mail->Body = $msg;
    
        $mail->send();
        echo 'Message has been sent';
    } catch (Exception $e) {
        echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
    }
}

?>






<!doctype html>
<html class="no-js" lang="zxx">


<head>

    <!--========= Required meta tags =========-->
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--====== Title ======-->
    <title>ATO Geophysical Limited - Geosciences Solution Provider in Nigeria</title>

    <!--====== Favicon ======-->
    <link rel="shortcut icon" href="assets/images/logo/favicon.ico" type="images/x-icon" />

    <!--====== CSS Here ======-->
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="assets/css/jquery-ui.min.css">
    <link rel="stylesheet" href="assets/css/lightcase.css">
    <link rel="stylesheet" href="assets/css/meanmenu.css">
    <link rel="stylesheet" href="assets/css/nice-select.css">
    <link rel="stylesheet" href="assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="assets/css/style.css">

</head>

<body>
   <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <!-- preloader  -->
    
    <!-- preloader end -->

    <!-- header start -->
    <header class="header">
        <div class="header__top">
            <div class="container-fluid">
                 <div class="row">
                     <div class="col-xl-6 col-lg-7 col-md-12">
                         <div class="header__top--info">
                             <ul>
                                 <li><a href="mailto:info@atogeophysical.com"><span class="icon"><i class="fal fa-envelope"></i></span> info@atogeophysical.com</a></li>
                                 <li><a href="tel:+2348027025333"><span class="icon"><i class="fal fa-phone"></i></span> +234 802 702 5333</a></li>
                             </ul>
                         </div>
                     </div>
                     <div class="col-xl-6 col-lg-5 col-md-12">
                        <div class="header__top--info--right">
                            <!-- <div class="lang">
                                <div class="lang__icon">
                                    <a href="#0" class="lang__btn">English <i class="fal fa-angle-down"></i></a>
                                    <ul class="lang__list">
                                        <li><a href="#0">USA</a></li>
                                        <li><a href="#0">UK</a></li>
                                        <li><a href="#0">CA</a></li>
                                        <li><a href="#0">AU</a></li>
                                    </ul>
                                </div>
                            </div> -->
                          <!-- <a href="careers.html" class="job-btn"><i class="fal fa-briefcase"></i> Get Job Feeds</a> -->
                        </div>
                     </div>
                 </div>
            </div>
        </div>
        <div class="navarea">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xl-2 col-lg-2 col-md-4 my-auto">
                        <div class="header__logo">
                            <a href="index.html">
                                <img src="assets/images/logo/fads.png" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-7 col-lg-7">
                        <div class="header__menu">
                            <nav id="mobile-menu">
                                <ul>
                                    <li><a href="index.html">Home </a></li>
                                    <li><a href="about.html">About Us</a></li>
                                    <li><a href="values.html">Values</a>
                                    <ul class="sub-menu">
                                        <li><a href="customers.html">Customers</a></li>
                                        <li><a href="people-power.html">People Power</a></li>
                                        <li><a href="community.html">Community</a></li>
                                        <li><a href="employee.html">Employee</a></li>
                                    </ul>
                                </li>
                                    <li><a href="services.html">Services</a></li>
                                    <li><a href="technology.html">Technology</a></li>
                                    <li><a href="team.html">Team</a></li>
                                    <li><a href="contact.html">Contact</a></li>
                                </ul>
                            </nav>
                            <div class="mobile-menu"></div>
                        </div>
                    </div>
                    <!-- <div class="col-xl-3 col-lg-3 col-md-8 my-auto d-none d-xl-block d-lg-block">
                        <div class="navarea__right">
                            <a href="contact.html" class="site-btn">Get A Quote <span>+</span></a>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </header>
    <!-- header end -->

    <!-- breadcrumb area start -->
    <section class="breadcrumb pt-150 pb-150 bg_img" data-background="aSssets/images/bg/breadcrumb-bg-1.jpg"
        data-overlay="dark" data-opacity="5">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="breadcrumb__wrap">
                        <h2 class="title">Contact Us</h2>
                        <div class="breadcrumb__nav">
                            <ul>
                                <li><span>//</span></li>
                                <li><a href="index.html">Home</a></li>
                                <li>|</li>
                                <li>Contact</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb area end -->

    <!-- cotact area start -->
    <div class="contact__area pt-100 pb-100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 text-center">
                    <div class="section__heading mb-50">
                        <h4 class="section__heading--title-small"><span class="mr-10">//</span>Contact Us<span class="ml-10">//</span></h4>
                        <h1 class="section__heading--transparent white">Enquiry</h1>
                        <h2 class="section__heading--title" style="font-size: 39px !important;">We are happy to work with you,for you<br> and together to achieve the object<span>.</span></h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-12">
                    <div class="contact__wrap pt-95 pb-95">
                        <div class="row justify-content-center">
                            <div class="col-xl-10">
                                <div class="contact__form">
                                    <form id="contacts-us-form" action="/contact.php" method="POST">
                                        <div class="row mt-none-30">
                                            <div class="col-xl-6 mt-30">
                                                <div class="form__group">
                                                    <label for="name"><i class="fal fa-user"></i></label>
                                                    <input name="name" type="text" id="name" placeholder="Enter your full name" required>
                                                </div>
                                            </div>
                                            <div class="col-xl-6 mt-30">
                                                <div class="form__group">
                                                    <label for="email"><i class="fal fa-envelope"></i></label>
                                                    <input name="email" type="email" id="email" placeholder="Enter email address" required>
                                                </div>
                                            </div>
                                            <div class="col-xl-6 mt-30">
                                                <div class="form__group">
                                                    <label for="tel"><i class="fal fa-phone"></i></label>
                                                    <input name="phone" type="tel" id="tel" placeholder="Add phone number" required>
                                                </div>
                                            </div>
                                            <div class="col-xl-6 mt-30">
                                                <div class="form__group">
                                                    <label for="subject"><i class="fal fa-book"></i></label>
                                                    <input name="subject" type="text" id="subject" placeholder="Enter your subject" required>
                                                </div>
                                            </div>
                                            <div class="col-xl-12 mt-30">
                                                <div class="form__group">
                                                    <label for="message"><i class="fal fa-pen"></i></label>
                                                    <textarea name="message" id="message" placeholder="Enter messages" required></textarea>
                                                </div>
                                            </div>
                                            <div class="col-xl-12 mt-30 text-center">
                                                <button class="site-btn" type="submit">Get Free Consultancy</button>
                                                <!-- <p class="ajax-response mt-15" style="color: #fff;"></p> -->
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- cotact area end -->

    <!-- contact info area start -->
    <div class="contactinfo__area">
        <div class="container">
            <div class="row mt-none-30">
                <div class="col-xl-4 col-lg-6 mt-30">
                    <div class="contact__info">
                        <div class="icon">
                            <i class="fal fa-map"></i>
                            <span><i class="fal fa-check"></i></span>
                        </div>
                        <div class="content">
                            <h2 class="title">Registered Office</h2>
                            <p>3, Ndidi Nwaka Street, off Akpofa Road GRA Benin City Edo State</p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6 mt-30">
                    <div class="contact__info contact__info--black">
                        <div class="icon">
                            <i class="fal fa-phone"></i>
                            <span><i class="fal fa-check"></i></span>
                        </div>
                        <div class="content">
                            <h2 class="title">Phone Number</h2>
                            <a href="tel:08105250032">0810 525 0032</a>
                            <!-- <a href="tel:76564856798">765 648 567 98</a> -->
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6 mt-30">
                    <div class="contact__info contact__info--blue">
                        <div class="icon">
                            <i class="fal fa-globe"></i>
                            <span><i class="fal fa-check"></i></span>
                        </div>
                        <div class="content">
                            <h2 class="title">Email</h2>
                            <a href="mailto:info@atogeophysical.com">info@atogeophysical.com</a>
                            <!-- <a href="mailto:Geosciences Solution Provider in Nigeriaample.com">Geosciences Solution Provider in Nigeriaample.com</a> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- contact info area end -->

    <!-- map area start -->
    <!-- <div id="contact-map"></div> -->
    <!-- map area end -->

    <!-- footer area start -->
    <footer class="site-footer bg_img pt-100" data-background="assets/images/pattern/footer-pattern.png">
        <div class="container">
            <div class="row">
                <div class="col-xl-12 text-center">
                    <a href="index.html" class="site-logo mb-50">
                        <img src="assets/images/logo/fads.png" alt="Logo">
                    </a>
                </div>
                <div class="col-xl-12">
                    <div class="footer-top mt-50 mb-80">
                        <div class="footer__info">
                            <div class="footer__info--item d-flex align-items-center">
                                <div class="icon mr-20">
                                    <img src="assets/images/icons/footer-info-icon-1.png" alt="">
                                </div>
                                <div class="content">
                                    <h4 class="title">Phone Number</h4>
                                    <a href="tel:98787676576577">0810 525 0032</a>
                                </div>
                            </div>
                            <div class="footer__info--item d-flex align-items-center">
                                <div class="icon mr-20">
                                    <img src="assets/images/icons/footer-info-icon-2.png" alt="">
                                </div>
                                <div class="content">
                                    <h4 class="title">Email Address</h4>
                                    <a href="mailto:info@atogeophysical.com">info@atogeophysical.com</a>
                                </div>
                            </div>
                            <div class="footer__info--item d-flex align-items-center">
                                <div class="icon mr-20">
                                    <img src="assets/images/icons/footer-info-icon-3.png" alt="">
                                </div>
                                <div class="content">
                                    <h4 class="title">Registered Office</h4>
                                    <span>3, Ndidi Nwaka Street, off Akpofa Road GRA Benin City Edo State</span>     
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="copyright-text">
                        <div class="row">
                            <div class="col-xl-12 text-center">
                                <p>Copyright ATO Geophysical Limited <span>2021</span></p> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer area end -->

    <!-- Fullscreen search -->
    <div class="search-wrap">
        <div class="search-inner">
            <i class="fal fa-times search-close" id="search-close"></i>
            <div class="search-cell">
                <form method="get">
                    <div class="search-field-holder">
                        <input type="search" class="main-search-input" placeholder="Search Your Keyword...">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- end fullscreen search -->

    <!--========= JS Here =========-->
    <script src="assets/js/jquery-2.2.4.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/jquery.meanmenu.min.js"></script>
    <script src="assets/js/jquery.nice-select.min.js"></script>
    <script src="assets/js/lightcase.js"></script>
    <script src="assets/js/owl.carousel.min.js"></script>
    <script src="assets/js/js_jquery.knob.js"></script>
    <script src="assets/js/js_jquery.appear.js"></script>
    <script src="assets/js/tilt.jquery.min.js"></script>
    <script src="assets/js/counterup.min.js"></script>
    <script src="assets/js/circle-progress.min.js"></script>
    <script src="assets/js/wow.min.js"></script>
    <script src="assets/js/waypoint.js"></script>
    <!-- <script src="assets/js/ajax-form.js"></script> -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDfpGBFn5yRPvJrvAKoGIdj1O1aO9QisgQ"></script>
    <script src="assets/js/main.js"></script>
</body>


</html>