<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

// use PHPMailer\PHPMailer\PHPMailer;
// use PHPMailer\PHPMailer\Exception;


// Load Composer's autoloader
require 'vendor/autoload.php';

// require 'vendor/PHPMailer/src/Exception.php';
// require 'vendor/PHPMailer/src/PHPMailer.php';
// require 'vendor/PHPMailer/src/SMTP.php';

// Instantiation and passing `true` enables exceptions
$mail = new PHPMailer(true);

if (isset($_POST['submit'])) {
    $from = $_POST['from'];
    $to = $_POST['to'];
    $cc = $_POST['cc'];
    $bcc = $_POST['bcc'];
    $subject = $_POST['subject'];
    $msg = $_POST['message'];

    try {
        //Server settings
        // $mail->SMTPDebug = SMTP::DEBUG_SERVER;

        // $mail->isSMTP(); 
        // $mail->Host       = 'smtp.mailtrap.io'; 
        // $mail->SMTPAuth   = true;
        // $mail->Username   = '192bf88d9c5bef';
        // $mail->Password   = 'a3636acac91698'; 
        // $mail->SMTPSecure = 'tls'; 
        // $mail->Port       = 2525;

        $mail->isSMTP();
        $mail->Host = 'smtp.mailtrap.io';
        $mail->SMTPAuth = true;
        $mail->Username = '192bf88d9c5bef'; //paste one generated by Mailtrap
        $mail->Password = 'a3636acac91698';//paste one generated by Mailtrap
        $mail->SMTPSecure = 'tls';
        $mail->Port = 2525;
    
        //Recipients
        $mail->setFrom($from);
        $mail->addAddress($to);
        $mail->addReplyTo($from);
        if(!empty($cc)){
            $mail->addCC($cc);
        }
        if(!empty($bcc)){
            $mail->addBCC($bcc);
        }
    
        // Attachments
        // $mail->addAttachment('/var/tmp/file.tar.gz');
        // $mail->addAttachment('/tmp/image.jpg', 'new.jpg');
    
        // Content
        $mail->isHTML(true);
        $mail->Subject = $subject;
        $mail->Body = $msg;
    
        $mail->send();
        echo 'Message has been sent';
    } catch (Exception $e) {
        echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
    }
}

?>

<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<script src="https://cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script>
</head>
<body>
    <div class="row justify-content-center">
        <div class="col-9">
            <div class="card">
                <div class="card-body">
                    <form method="POST" action="">
                        <div class="row">
                            <div class="col">
                                <input name="from" class="form-control mb-4" placeholder="From:" />
                            </div>
                            <div class="col">
                                <input name="to" class="form-control mb-4" placeholder="To:" />
                            </div>
                        </div>
                        <input name="cc" class="form-control mb-4" placeholder="CC:" />
                        <input name="bcc" class="form-control mb-4" placeholder="BCC:" />
                        <input name="subject" class="form-control mb-4" placeholder="Subject:" />
                        <textarea name="message" class="form-control" placeholder="Message:"></textarea>
                        <button type="submit" name="submit" class="btn btn-primary mt-4">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        CKEDITOR.replace( 'message' );
    </script>
</body>
</html>